### ISSUE TITLE
Right aligned text

### ISSUE THREAD

**Issue by spassvogel** [Skjalgsm/PolyglotUnity#12]
I have some (English) text in a `Text` Component that has a `LocalizedText`. However, when the text gets translated, it automatically gets aligned to the left because of `protected override void UpdateAlignment(Text text, LanguageDirection direction)` ...

I would like to see an option on `LocalizedText` to maintain the original text alignment. Do you accept pull requests?

**Comment by skjalgsm** [comment]
Yep. I’m planning on doing something about this as it has been bugging me
to. What are your proposed changes?

man. 10. sep. 2018 kl. 10:35 skrev Wouter van den Heuvel <
notifications@github.com>:

**Comment by spassvogel** [comment]
Well perhaps a `boolean` on `LocalizedTextComponent` that prevents changing of text alignment? It could default to `false` to keep the existing behaviour.

That way you can set it per unity component instance.

**Comment by spassvogel** [comment]
Something like this: https://github.com/agens-no/PolyglotUnity/pull/13
