### ISSUE TITLE
in script usage

### ISSUE THREAD

**Issue by ms502040** [Skjalgsm/PolyglotUnity#15]
Hi,
if is possible use this plugin from script can you write some docs?

**Comment by skjalgsm** [comment]
Yes. What exactly do you need help with?

tor. 17. jan. 2019 kl. 09:56 skrev Mira <notifications@github.com>:

**Comment by ms502040** [comment]
some example or documentation. i can't found in repository.

**Comment by skjalgsm** [comment]
https://github.com/agens-no/PolyglotUnity/blob/master/README.md
