### ISSUE TITLE
Checks for start and end of parsing

### ISSUE THREAD

**Issue by JohannesDeml** [Skjalgsm/PolyglotUnity#16]
I just had the problem that my localization filw was not parsed anymore, even though I just added three simple strings to the file. After quite a while I found the problem: One added ID was "ENDSCREEN_BUTTON", which triggered `if(key.StartsWith("END"))` in LocalizationImporter.cs.

I think another convention than checking if the string starts with END would be benefitial for the project. I suggest to check for an equals instead of using `StartsWith()`. To stay consistent I propose to do this change for the start as well. So the code would change to 

```
if (!canBegin)
{
    if (key == "Polyglot" || key == "PolyMaster" || key == "BEGIN")
    {
        canBegin = true;
    }
    continue;
}

if (key == "END")
{
    break;
}
```

If this is in the interest of those involved I would create a PR for it :)

**Comment by skjalgsm** [comment]
Yeah this makes sense. Pleasw make a PR :)

fre. 8. feb. 2019 kl. 12:31 skrev Johannes Deml <notifications@github.com>:

**Comment by JohannesDeml** [comment]
Awesome, thanks for the quick response! ❤
