### ISSUE TITLE
is this repo still active?

### ISSUE THREAD

**Issue by sgamerw** [Skjalgsm/PolyglotUnity#18]
Awesome project you guys have made, but it seems like nobody maintain this project any more, issues and pr exists for long time, I used PolyglotUnity in my game and I really like it, I have fixed some bugs and added some features for it, so if you guys still maintain this repo, I'd like to pull some requests, or I want to fork this repo to maintain this great plugin by myself and continue making it better, hope for your reply.

**Comment by skjalgsm** [comment]
Sure thing sgamerw, pull request away :)

**Comment by sgamerw** [comment]
Great, glad to contribute for this.
