### ISSUE TITLE
Handling of Selected Language with ScriptableObject

### ISSUE THREAD

**Issue by henriqueranj** [Skjalgsm/PolyglotUnity#19]
Hello,

When changing the selected language via code, I am using (e.g.) `Localization.SelectedLanguage = Language.Dutch`. This has a caveat as is it will change the serialized field `selectedLanguage` in the Localization ScriptableObject. This can cause some difficulties in the Unity Editor when working in a team and everyone starts seeing changes to this file.

Is this the correct way to change the selected language in run-time? If so, could a separate approach be considered for the selected language? (ie, do not set the serialized field but another cached field instead?)

**Comment by skjalgsm** [comment]
Yes a different approach seems fair. I’d expext hide flags to be set in
runtime as DontSave so that this doesnt happeb

man. 20. mai 2019 kl. 13:50 skrev Henrique Campos <notifications@github.com

**Comment by skjalgsm** [comment]
Feel free to create a PR with this change if you'd like
