### ISSUE TITLE
LocalizedTextComponent.AddParameter(..) does not work for strings with more than 1 parameter

### ISSUE THREAD

**Issue by henriqueranj** [Skjalgsm/PolyglotUnity#23]
In the `LocalizedTextComponent`, the methods to add parameters `AddParameter(..)` triggers an error - [FormatException](https://docs.microsoft.com/en-us/dotnet/api/system.formatexception?view=netframework-4.8) - if the given string to format requires more than 1 parameter. 

This is because every time a parameter is added via these methods, it will call `OnLocalize()` and thus try to format the string with the first added parameter. And currently the API does not contain a method to add a set of parameters at once.

As an example:
- I have the localized string: `Hello, my name is {0} and I work as {1}`
- Then by calling AddParameter("Bob"), it will trigger the FormatException error as it will immediately try to format the string.

As a workaround I added a method `SetParameters(params object[] parameters)` in the `LocalizedTextComponent`:
```
public void SetParameters(params object[] parameters) {
  ClearParameters();
  this.parameters.AddRange(parameters);
  OnLocalize();
}
```
Could this method be an alternative to the `AddParameter()` methods?

**Comment by skjalgsm** [comment]
https://github.com/agens-no/PolyglotUnity/commit/142db947954147bf2507587ea4c96d9a6eaaaf92
