### ISSUE TITLE
Readme Instructions - 'line 7'

### ISSUE THREAD

**Issue by Vixxd** [Skjalgsm/PolyglotUnity#24]
Hey there, great tool & great spreadsheet. I have a quick query about the README.

I've copied & duplicated the sheet, but the following line is confusing me:

`Duplicate the polyglot master sheet and remove all the keys from line 7. The importer parses everything 
line after the term "polyglot", "PolyMaster" or "BEGIN".`

Do you mean 'line 6'? Or do I need to leave in 'polyglot' so it begins parsing after that?

![image](https://user-images.githubusercontent.com/5870958/75774334-ade8d580-5d47-11ea-9717-67e1a0a3ef0c.png)

(I'm sure I'll have an answer after actually testing it - however, just posting this here so I can refer back to it & request to update the README if necessary)

**Comment by Team-on** [comment]
It just work without deleting anything
