### ISSUE TITLE
Unity 5.6 compilation error regarding UnityWebRequest in GoogleDownload class

### ISSUE THREAD

**Issue by runevision** [Skjalgsm/PolyglotUnity#27]
The integration produces the following compile error in Unity 5.6:

Assets/Polyglot/Scripts/GoogleDownload.cs(25,23): error CS0103: The name `UnityWebRequest' does not exist in the current context

Changing line 4 from UNITY_2017_2_OR_NEWER to UNITY_5_5_OR_NEWER seems to fix it.

**Comment by skjalgsm** [comment]
This should be fixed in https://github.com/agens-no/PolyglotUnity/commit/7aee54adb419cb90056a789cdc8ad9515376c585
