### ISSUE TITLE
Compilation error regarding CanCacheInspectorGUI in LocalizedStringAttributeDrawer

### ISSUE THREAD

**Issue by runevision** [Skjalgsm/PolyglotUnity#28]
The method CanCacheInspectorGUI needs to be wrapped in #if UNITY_2017_3_OR_NEWER

**Comment by runevision** [comment]
Same in LocalizedStringDrawer.

**Comment by skjalgsm** [comment]
This should be fixed in https://github.com/agens-no/PolyglotUnity/commit/7aee54adb419cb90056a789cdc8ad9515376c585
