### ISSUE TITLE
Error after Import: Assets/Polyglot/Editor/LocalizationEditor.cs(226,17): error CS1061: Type `UnityEngine.Networking.UnityWebRequest' does not contain a definition for `SendWebRequest' and no extension method `SendWebRequest' of type `UnityEngine.Networking.UnityWebRequest' could be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by spaggi2** [Skjalgsm/PolyglotUnity#5]
Hi,

I imported the Asset Folder contents into my 2017.1.1f1 project and am getting the following Error now:
`
Assets/Polyglot/Editor/LocalizationEditor.cs(226,17): error CS1061: Type `UnityEngine.Networking.UnityWebRequest' does not contain a definition for `SendWebRequest' and no extension method `SendWebRequest' of type `UnityEngine.Networking.UnityWebRequest' could be found. Are you missing an assembly reference?`

Indeed, the Class UnityWebRequest does not contain mentioned Method

Also, could you clarify the install instrucions a bit? There are the project files as well as 2 unity packages. What is the correct install procedure? 

Thank you, this tool looks really awesome!

**Comment by Biodam** [comment]
Hello I'm using version 2018.1.0f2 and didn't have this problem.

About the installation process I used the 1.3 Unity package to import it in my project and it seems to be working fine. Didn't test the custom sheet yet though.

**Comment by skjalgsm** [comment]
fixed in https://github.com/agens-no/PolyglotUnity/commit/f6cce1b7bb164bc00653f54ec6e21af0186078a2
