### ISSUE TITLE
Automation suggestions

### ISSUE THREAD

**Issue by Biodam** [Skjalgsm/PolyglotUnity#8]
Hi, I have some suggestions for some tasks that could be automated to improve usability.

1. Add the custom sheet TextAsset to the input files in the first download
1. Parse the custom sheet after the download is complete
1. Change the text in the UI.Text/TMP.Text component when changing the key in the localization script

**Comment by skjalgsm** [comment]
Fixed in https://github.com/agens-no/PolyglotUnity/commit/4abe355611a1445fd95c4bcc990f920c885e54bf
